services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: db-for-go
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_unicode_ci
    - --sql-mode=ONLY_FULL_GROUP_BY,NO_ENGINE_SUBSTITUTION
    environment:
      MYSQL_ROOT_USER: ${ROOTUSER}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  go-api:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: build/Dockerfile  # Dockerfileが build ディレクトリ内にあるため
    container_name: go-api
    environment:
      DOCKER_ENV: "true"
      DATABASE: ${DATABASE}
      USERNAME: ${USERNAME}
      USERPASS: ${USERPASS}
      DBHOST: mysql
      DBPORT: ${DBPORT}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy # mysqlのhealthcheckが成功したら起動

volumes:
  db-volume:
