global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ecs-node-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['${ALB_DNS_NAME}']
    scheme: http
